[server]
    MaxHeaderBytes    = "20KB"
    ClientMaxBodySize = "5MB"

[database]
       Host         = "127.0.0.1"
       Port         = "3306"
       User         = "root"
       Pass         = "root"
       Name         = "task_platform"
       Type         = "mysql"